Merge request CSCFC4EMSCR-470 Add namespace as an editable field for schemas to develop branch
CSCfi/mscr-ui-monorepo pull request #212
Opened 2024-09-24 12:46 UTC by masillan

Merge request to develop branch. CSCFC4EMSCR-470 Add namespace as an editable field for schemas implementation. Namespace can now be edited and changed.

2024-09-24 15:14 UTC, maariaw requested changes
Need to remove the changes to package-lock. Otherwise all clear.

2024-09-24 15:14 UTC, maariaw commented on package-lock.json
Should leave out these changes to package-lock.json. It's weird that it isn't in the gitignore, but we can discuss that separately.

2024-09-25 07:41 UTC, masillan commented on package-lock.json
Nice to have a comment. I had a monologue on this matter on MSCR Rocket Chat channel.

2024-09-26 07:11 UTC, maariaw approved these changes
OK

2024-09-26 07:40 UTC, merged